# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
generate:
  models: true
  client: true
  embedded-spec: true
  server-urls: true
